### ISSUE TITLE
Serialize and Deserialize

### ISSUE THREAD

**Issue by Aarth-Tandel** [petrkovac/iforest#1]
Hey, 
I am not getting the use or Serialize and Deserialize class methods in the header file. It would be really helpful if I can get insight on the same,

**Comment by petrkovac** [comment]
Hi, these functions are used to store (Serialize) and load (Deserialize) the Isolation Forest to/from disk like this:

```c++
iforest::IsolationForest<ValueType, dimensionCount> forest;

// build the forest...

// save it
std::string forestFile = "forest.bin";
std::ofstream ofs(forestFile, std::ios::binary);

if (!forest.Serialize(ofs))
{
	std::cerr << "Failed to serialize forest to file: " << forestFile << std::endl;
	return -1;
}

// do something else

// load the forest
std::ifstream ifd(forestFile, std::ios::binary);

if (!forest.Deserialize(ifd))
{
	std::cerr << "Failed to reconstruct isolation forest from: " << forestFile << std::endl;
	return -1;
}
```
Hope this helps.

**Comment by Aarth-Tandel** [comment]
Can we modify the header file to take vector of vector instead of vector of array?. I tried understanding the code but I was unable to convert it. 

`iforest::IsolationForest<double, 2> forest;`

I want to pass a variable dimension to the Forest header file and was unable to do so. 

Any help will be really useful

**Comment by petrkovac** [comment]
No that is not possible, the dimension must be known at compile time.

**Comment by Aarth-Tandel** [comment]
Is there any specific reason why we need to write tree on disk? because I removed those function, but the output remained the same.

**Comment by petrkovac** [comment]
No, you do not need to do that. Its an utility function that might be useful in some specific use cases.
