### ISSUE TITLE
"Seed"

### ISSUE THREAD

**Issue by sahendrapang** [petrkovac/iforest#2]
Hi,

I would like to ask what is the "uint32_t seed" refer to in the 
bool Build(uint32_t treeCount, uint32_t seed, std::vector<item_t>& data, uint32_t sampleSize) fundtion

Regards

**Comment by petrkovac** [comment]
Hi, the seed is used to initialize the random number generator.
This generator is then used to randomly choose a dimension where to split the tree in each step. Using the same seed every time will produce the same tree, which is useful for testing or deterministic experiments. In production one would use a different seed every time (for example the current system time).
